apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ktkeutdz
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ktkeutdz:a6297f0f49f8a0340280c85f98da7fcf7bd1ca2c@sha256:77a2958e3bc0532d73b77d0de6bc4a6bcc2b83035559fb8cc93a9391303924d9
        name: container-image  
